Sprint 2/step 2
milashkina/react-burger pull request #6
Opened 2023-10-18 15:48 UTC by milashkina

2023-10-18 17:25 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Используется redux;
- Реализован DnD;

### **Но есть несколько замечаний, которые нужно исправить:**

- Кажется, тут что-то пошло не так, нужно сменить регистр начальной буквы (чтобы было как у остальных файлов) <https://disk.yandex.com/i/iAeFfjnbhpp5IQ>. Ну и заодно, лучше поменять расширение `.js` на `.jsx`, там где есть `jsx`.

- <https://disk.yandex.com/i/QbS2atkplxXWww> - текст тоже должен выделиться;

- В запросе `/orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/PisaiJgFlkUaOA>;

- Необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

  Пример как правильно:

  ```js
  data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
  ```

- Не нужно использовать key, если мы не итерируем jsx элемент.

  Советую освежить в памяти: <https://ru.react.js.org/docs/lists-and-keys.html>

### **Сделает код лучше:**

- По умолчанию булок быть не должно - <https://disk.yandex.com/i/-Cbp_peSJ3FuPA>;

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-10-18 17:25 UTC, ArslanMustafin commented on src/components/ingredient-card/ingredient-card.js
> +    }
**Надо исправить:**

Во многих компонентах будет дублироваться описание PropTypes ингредиента.
Следует вынести его в отдельный файл (можно создать файл `prop-types.js` в папке `utils`) и переиспользовать описание пропсов ингредиента, а не дублировать;

2023-10-18 17:25 UTC, ArslanMustafin commented on src/components/product-list/product-list.js
> +  ingredients: PropTypes.arrayOf(PropTypes.shape(
**Надо исправить:**

Во многих компонентах будет дублироваться описание PropTypes ингредиента.
Следует вынести его в отдельный файл (можно создать файл `prop-types.js` в папке `utils`) и переиспользовать описание пропсов ингредиента, а не дублировать;

2023-10-18 17:25 UTC, ArslanMustafin commented on src/components/constructor-card/constructor-card.js
> +    <div key={nanoid()} ref={ref} className={`${style.wrapperConstructor}`} style={{ opacity }}>
**Надо исправить:**

тут не нужно использовать key, т.к. мы не итерируем jsx элемент.

Советую освежить в памяти: https://ru.react.js.org/docs/lists-and-keys.html

2023-10-18 17:25 UTC, ArslanMustafin commented on src/components/ingredient-card/ingredient-card.js
> +    <div key={id} ref={dragRef} onClick={() => onSelect(ingredient)} className={isDragging ? `${style.borderAccent}` : ''} >
**Надо исправить:**

тут не нужно использовать key, т.к. мы не итерируем jsx элемент.

Советую освежить в памяти: https://ru.react.js.org/docs/lists-and-keys.html

2023-10-18 17:25 UTC, ArslanMustafin commented on src/services/reducers/burger-constructor.js
> +    }
Не очень понял что вы хотели этим сказать.

2023-10-18 17:25 UTC, ArslanMustafin commented on src/services/reducers/burger-ingredients.js
> +            }
**Можно лучше:**

Возможно тут лучше сделать тернарку, читабильность повыситься.

```js
const quantity = ingredient._id === action._id ? 2 : 0;

return {...ingredient, quantity };
```

2023-10-18 17:25 UTC, ArslanMustafin commented on src/services/reducers/burger-ingredients.js
> +        bun: { ...action.bun, quantity: action.bun.quantity += 2},
**Надо исправить:**

а откуда тут появилось это поле?

2023-10-18 17:25 UTC, ArslanMustafin commented on src/services/reducers/order-info.js
> +        console.log(res)
**Можно лучше:**

Старайтесь не оставлять код-дебагинга и прочее, когда отправляете работу на проверку.

2023-10-18 17:25 UTC, ArslanMustafin commented on src/components/burger-ingredients/Burger-ingredients.js
> +  }
**Можно лучше:**

Если есть чуток лишнего времени, то очень рекомендую исправить.

У вас тут происходит очень много вызовов экшенов, т.к. это идёт при скролле.
Попробуйте использовать библиотеку `react-intersection-observer`, она вам поможет определять тот момент когда элемент входит в область просмотра или покидает ее. И не будет так много вызовов)) 

А также не стоит хранить это всё в сторе, т.к. информация о табе нужна только на этой странице)

2023-10-20 07:40 UTC, milashkina commented on src/components/ingredient-card/ingredient-card.js
> +    }
создала константу для этого в уже существующем файле с константами

2023-10-20 13:58 UTC, ArslanMustafin commented on src/services/reducers/burger-ingredients.js
> +        bun: { ...action.bun, quantity: action.bun.quantity += 2},
@milashkina, точно ли нужно это поле тут? по идее его тут быть не должно))

2023-10-20 14:47 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Практически все замечания были исправлены.

### **Рекомендую исправить:**

- Лучше исправить следующие замечание: <https://github.com/milashkina/react-burger/pull/6#discussion_r1364243940>

2023-10-20 14:54 UTC, milashkina commented on src/services/reducers/burger-ingredients.js
> +        bun: { ...action.bun, quantity: action.bun.quantity += 2},
> @milashkina, точно ли нужно это поле `bun` тут? по идее его тут быть не должно))

утром казалось что нужно. Сейчас понимаю что нет) спасибо, уберу 84 строку и запушу

2023-10-20 14:57 UTC, merged